ALTER TABLE items
 DROP dmg_min3,
 DROP dmg_max3,
 DROP dmg_type3,
 DROP dmg_min4,
 DROP dmg_max4,
 DROP dmg_type4,
 DROP dmg_min5,
 DROP dmg_max5,
 DROP dmg_type5,
 CHANGE COLUMN `field4` `unknown_bc` INT(10) NOT NULL DEFAULT '-1',
 -- ADD unknown_tlk INT(10) NOT NULL DEFAULT '-1' AFTER unknown_bc,
 ADD Faction INT(30) UNSIGNED NOT NULL DEFAULT '3' AFTER flags,
 ADD ScaledStatsDistributionId INT(32) UNSIGNED NOT NULL DEFAULT '0' AFTER stat_value10,
 ADD ScaledStatsDistributionFlags INT(32) UNSIGNED NOT NULL DEFAULT '0'AFTER ScaledStatsDistributionId,
 CHANGE COLUMN `unk2` `ArmorDamageModifier` INT(30) NOT NULL DEFAULT '0',
 ADD ExistingDuration INTEGER NOT NULL DEFAULT '0',
 ADD ItemLimitCategory INT(30) NOT NULL DEFAULT '0' AFTER ExistingDuration,
 ADD HolidayId INT(30) NOT NULL DEFAULT '0';