ALTER TABLE ai_agents
ADD MiscEvent1 INT(11) UNSIGNED NOT NULL DEFAULT '0' AFTER Misc2,
ADD MiscEvent1_Val INT(11) UNSIGNED NOT NULL DEFAULT '0' AFTER MiscEvent1,
ADD MiscEvent1_Count INT(11) UNSIGNED NOT NULL DEFAULT '0' AFTER MiscEvent1_Val,
ADD MiscEvent2 INT(11) UNSIGNED NOT NULL DEFAULT '0' AFTER MiscEvent1_Count,
ADD MiscEvent2_Val INT(11) UNSIGNED NOT NULL DEFAULT '0' AFTER MiscEvent2,
ADD MiscEvent2_Count INT(11) UNSIGNED NOT NULL DEFAULT '0' AFTER MiscEvent2_Val,
ADD MiscEvent3 INT(11) UNSIGNED NOT NULL DEFAULT '0' AFTER MiscEvent2_Count,
ADD MiscEvent3_Val INT(11) UNSIGNED NOT NULL DEFAULT '0' AFTER MiscEvent3,
ADD MiscEvent3_Count INT(11) UNSIGNED NOT NULL DEFAULT '0' AFTER MiscEvent3_Val;