ALTER TABLE quests
 ADD ReqOrRecItemId5 INT(10) unsigned NOT NULL DEFAULT '0' AFTER ReqOrRecItemId4,
 ADD ReqOrRecItemId6 INT(10) unsigned NOT NULL DEFAULT '0' AFTER ReqOrRecItemId5,
 ADD ReqOrRecItemCount5 INT(10) unsigned NOT NULL DEFAULT '0' AFTER ReqOrRecItemCount4,
 ADD ReqOrRecItemCount6 INT(10) unsigned NOT NULL DEFAULT '0' AFTER ReqOrRecItemCount5;
 /*CHANGE ReqOrRecItemId1 ReqOrRecItemId1 INT(10) UNSIGNED NOT NULL DEFAULT '0' AFTER ObjectiveText4,
 CHANGE ReqOrRecItemId2 ReqOrRecItemId2 INT(10) UNSIGNED NOT NULL DEFAULT '0' AFTER ReqOrRecItemId1,
 CHANGE ReqOrRecItemId3 ReqOrRecItemId3 INT(10) UNSIGNED NOT NULL DEFAULT '0' AFTER ReqOrRecItemId2,
 CHANGE ReqOrRecItemId4 ReqOrRecItemId4 INT(10) UNSIGNED NOT NULL DEFAULT '0' AFTER ReqOrRecItemId3,
 CHANGE ReqOrRecItemId5 ReqOrRecItemId5 INT(10) UNSIGNED NOT NULL DEFAULT '0' AFTER ReqOrRecItemId4,
 CHANGE ReqOrRecItemId6 ReqOrRecItemId6 INT(10) UNSIGNED NOT NULL DEFAULT '0' AFTER ReqOrRecItemId5,
 CHANGE ReqOrRecItemCount1 ReqOrRecItemCount1 INT(10) UNSIGNED NOT NULL DEFAULT '0' AFTER ReqOrRecItemId6,
 CHANGE ReqOrRecItemCount2 ReqOrRecItemCount2 INT(10) UNSIGNED NOT NULL DEFAULT '0' AFTER ReqOrRecItemCount1,
 CHANGE ReqOrRecItemCount3 ReqOrRecItemCount3 INT(10) UNSIGNED NOT NULL DEFAULT '0' AFTER ReqOrRecItemCount2,
 CHANGE ReqOrRecItemCount4 ReqOrRecItemCount4 INT(10) UNSIGNED NOT NULL DEFAULT '0' AFTER ReqOrRecItemCount3,
 CHANGE ReqOrRecItemCount5 ReqOrRecItemCount5 INT(10) UNSIGNED NOT NULL DEFAULT '0' AFTER ReqOrRecItemCount4,
 CHANGE ReqOrRecItemCount6 ReqOrRecItemCount6 INT(10) UNSIGNED NOT NULL DEFAULT '0' AFTER ReqOrRecItemCount5,
 CHANGE RequiredPlayer RequiredPlayer INT(10) NOT NULL DEFAULT '0' AFTER ReqOrRecItemCount6;*/