#!/usr/bin/env sh

# SVN Revision Extractor for Unix systems
# Written by Burlex, 2008/02/20
# ReWritten by Franck77, 2008/06/16

cmd="svn info http://opensvn.csie.org/WaadDev/ | grep 'vision :' | cut -d' ' -f3"
rev=`eval $cmd`
cmd="cat ascent-tag"
tag=`eval $cmd`

echo "// This file was automatically generated by the SVN revision extractor." > svn_revision.h
echo "// There is no need to modify it." >> svn_revision.h
echo "" >> svn_revision.h
echo "#ifndef SVN_REVISION_H" >> svn_revision.h
echo "#define SVN_REVISION_H" >> svn_revision.h
echo "" >> svn_revision.h
echo "static const char * BUILD_TAG = \"$tag\";" >> svn_revision.h
echo "static int BUILD_REVISION = $rev;" >> svn_revision.h
echo "" >> svn_revision.h
echo "#endif         // SVN_REVISION_H" >> svn_revision.h
echo "" >> svn_revision.h

mv svn_revision.h src/ascent-shared

echo "Rev: $rev Tag: $tag"
