// This file was automatically generated by the SVN revision extractor.
// There is no need to modify it.

#ifndef SVN_REVISION_H
#define SVN_REVISION_H

static const char * BUILD_TAG = "-TRUNK335-EXPERIMENTALE-";
static int BUILD_REVISION = 466;

#endif		 // SVN_REVISION_H

